<a href="https://colab.research.google.com/github/Fer-2022/Procesos-Estocasticos-ESFM-IPN/blob/main/ACTIVIDAD_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="color:#D12B2B; font-size:28px; font-weight:bold;">
  Ejercicio 3: Aproximación de P(t) para una CMTC
</p>

<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Problema: Calcular P(0.5), P(1) y P(5) usando la serie infinita aproximada con los primeros M términos.
</p>

<p style="font-size:18px;">
  Usaremos la fórmula:
</p>

<p style="font-size:20px; font-weight:bold;">
  P(t)=Σ e^(-rt) ((rt)^k / k!) P_hat^k
</p>

<p style="font-size:18px;">
  En este ejercicio se usa r = 6 y la matriz R del ejercicio anterior.
</p>

In [1]:
import numpy as np
import math

# Matriz de tasas R del ejercicio anterior
R = np.array([
    [0, 2, 3, 0],
    [4, 0, 2, 0],
    [0, 2, 0, 2],
    [1, 0, 3, 0]
], dtype=float)

# Valor dado de r
r = 6

# Calculamos r_i como la suma de cada fila
r_i = R.sum(axis=1)

print("Matriz R:")
print(R)

print("\nValores de r_i:")
print(r_i)

Matriz R:
[[0. 2. 3. 0.]
 [4. 0. 2. 0.]
 [0. 2. 0. 2.]
 [1. 0. 3. 0.]]

Valores de r_i:
[5. 6. 4. 4.]


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Construcción de la matriz P_hat
</p>

<p style="font-size:18px;">
  Para construir P_hat usamos:
</p>

<p style="font-size:20px; font-weight:bold;">
  p_hat_ii = 1 - r_i/r
</p>

<p style="font-size:20px; font-weight:bold;">
  p_hat_ij = r_ij/r, cuando i ≠ j
</p>

In [2]:
# Construimos P_hat
n = R.shape[0]
P_hat = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i == j:
            P_hat[i, j] = 1 - r_i[i] / r
        else:
            P_hat[i, j] = R[i, j] / r

print("Matriz P_hat:")
print(P_hat)

print("\nComprobación de suma por filas:")
print(P_hat.sum(axis=1))

Matriz P_hat:
[[0.16666667 0.33333333 0.5        0.        ]
 [0.66666667 0.         0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.16666667 0.         0.5        0.33333333]]

Comprobación de suma por filas:
[1. 1. 1. 1.]


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Elección de M
</p>

<p style="font-size:18px;">
  El problema recomienda usar:
</p>

<p style="font-size:20px; font-weight:bold;">
  M ≈ max{rt + 5√rt, 20}
</p>

<p style="font-size:18px;">
  Como debemos calcular P(0.5), P(1) y P(5), calcularemos M para cada valor de t.
</p>

In [3]:
def calcular_M(t, r):
    return math.ceil(max(r*t + 5*math.sqrt(r*t), 20))

for t in [0.5, 1, 5]:
    print(f"Para t = {t}, M = {calcular_M(t, r)}")

Para t = 0.5, M = 20
Para t = 1, M = 20
Para t = 5, M = 58


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Función para calcular P(t)
</p>

<p style="font-size:18px;">
  Esta función aproxima P(t) sumando los primeros M términos de la serie:
</p>

<p style="font-size:20px; font-weight:bold;">
  P(t)=Σ e^(-rt) ((rt)^k / k!) P_hat^k
</p>

In [4]:
def calcular_P_t(P_hat, r, t):
    n = P_hat.shape[0]
    M = calcular_M(t, r)

    P_t = np.zeros((n, n))
    P_hat_k = np.eye(n)

    for k in range(M + 1):
        coeficiente = math.exp(-r*t) * ((r*t)**k) / math.factorial(k)
        P_t += coeficiente * P_hat_k

        P_hat_k = P_hat_k @ P_hat

    return P_t, M

<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Cálculo de P(0.5), P(1) y P(5)
</p>

<p style="font-size:18px;">
  Ahora calculamos las matrices de transición para los tres tiempos solicitados.
</p>

In [5]:
tiempos = [0.5, 1, 5]
resultados = {}

for t in tiempos:
    P_t, M = calcular_P_t(P_hat, r, t)
    resultados[t] = P_t

    print(f"\nP({t}) usando M = {M}:")
    print(np.round(P_t, 6))

    print("Suma por filas:")
    print(np.round(P_t.sum(axis=1), 6))


P(0.5) usando M = 20:
[[0.250609 0.216965 0.386657 0.14577 ]
 [0.253135 0.238361 0.374409 0.134095]
 [0.169119 0.193615 0.420301 0.216965]
 [0.158017 0.157445 0.398332 0.286206]]
Suma por filas:
[1. 1. 1. 1.]

P(1) usando M = 20:
[[0.206151 0.203902 0.39871  0.191236]
 [0.208284 0.205341 0.397899 0.188474]
 [0.196758 0.198379 0.400959 0.203902]
 [0.192046 0.193997 0.401471 0.212484]]
Suma por filas:
[0.999999 0.999999 0.999999 0.999999]

P(5) usando M = 58:
[[0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]
 [0.2      0.2      0.399999 0.2     ]]
Suma por filas:
[0.999998 0.999998 0.999998 0.999998]


<p style="color:#D12B2B; font-size:28px; font-weight:bold;">
  Verificación de Chapman-Kolmogorov
</p>

<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Se debe verificar si P(1) = P(0.5)P(0.5)
</p>

<p style="font-size:18px;">
  Calcularemos P(0.5)P(0.5) y lo compararemos con P(1).
</p>

In [6]:
P_05 = resultados[0.5]
P_1 = resultados[1]

producto = P_05 @ P_05

print("P(1):")
print(np.round(P_1, 6))

print("\nP(0.5)P(0.5):")
print(np.round(producto, 6))

print("\nDiferencia P(1) - P(0.5)P(0.5):")
print(np.round(P_1 - producto, 10))

P(1):
[[0.206151 0.203902 0.39871  0.191236]
 [0.208284 0.205341 0.397899 0.188474]
 [0.196758 0.198379 0.400959 0.203902]
 [0.192046 0.193997 0.401471 0.212484]]

P(0.5)P(0.5):
[[0.206151 0.203902 0.39871  0.191236]
 [0.208285 0.205341 0.3979   0.188475]
 [0.196759 0.19838  0.400959 0.203902]
 [0.192047 0.193997 0.401472 0.212485]]

Diferencia P(1) - P(0.5)P(0.5):
[[-2.91e-07 -2.91e-07 -5.82e-07 -2.91e-07]
 [-2.91e-07 -2.91e-07 -5.82e-07 -2.91e-07]
 [-2.91e-07 -2.91e-07 -5.82e-07 -2.91e-07]
 [-2.91e-07 -2.91e-07 -5.82e-07 -2.91e-07]]


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Conclusión
</p>

<p style="font-size:18px;">
  Si la diferencia entre P(1) y P(0.5)P(0.5) es muy cercana a cero, entonces se verifica la ecuación de Chapman-Kolmogorov.
</p>

In [7]:
diferencia = np.linalg.norm(P_1 - producto)

print("Norma de la diferencia:")
print(diferencia)

if diferencia < 1e-6:
    print("\nConclusión: Sí se verifica Chapman-Kolmogorov.")
else:
    print("\nConclusión: No se verifica exactamente, pero la diferencia se debe a la aproximación numérica.")

Norma de la diferencia:
1.539915535128435e-06

Conclusión: No se verifica exactamente, pero la diferencia se debe a la aproximación numérica.


<p style="font-size:18px;">
  Conclusión: Sí se verifica la ecuación de Chapman-Kolmogorov, ya que la matriz P(1) es prácticamente igual al producto P(0.5)P(0.5). Las pequeñas diferencias que puedan aparecer se deben a la aproximación numérica de la serie infinita.
</p>

<p style="color:#D12B2B; font-size:28px; font-weight:bold;">
  Ejercicio 4.2: Algoritmo de uniformización para calcular P(t)
</p>

<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Problema: Repetir el ejercicio 3 usando el algoritmo de uniformización con tolerancia ε = 0.00001.
</p>

<p style="font-size:18px;">
  El objetivo es calcular P(0.5), P(1) y P(5), indicando el valor de M utilizado en cada caso.
</p>

In [1]:
import numpy as np
import math

<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Datos del problema
</p>

<p style="font-size:18px;">
  Usaremos la matriz de tasas R del ejercicio anterior y el valor r = 6.
</p>

In [2]:
R = np.array([
    [0, 2, 3, 0],
    [4, 0, 2, 0],
    [0, 2, 0, 2],
    [1, 0, 3, 0]
], dtype=float)

r = 6
epsilon = 0.00001

print("Matriz R:")
print(R)

print("\nr =", r)
print("epsilon =", epsilon)

Matriz R:
[[0. 2. 3. 0.]
 [4. 0. 2. 0.]
 [0. 2. 0. 2.]
 [1. 0. 3. 0.]]

r = 6
epsilon = 1e-05


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Construcción de la matriz P_hat
</p>

<p style="font-size:18px;">
  Primero calculamos r_i como la suma de cada fila de R.
</p>

<p style="font-size:18px;">
  Después usamos:
</p>

<p style="font-size:20px; font-weight:bold;">
  p_hat_ii = 1 - r_i/r
</p>

<p style="font-size:20px; font-weight:bold;">
  p_hat_ij = r_ij/r, si i ≠ j
</p>

In [3]:
r_i = R.sum(axis=1)

n = R.shape[0]
P_hat = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i == j:
            P_hat[i, j] = 1 - r_i[i] / r
        else:
            P_hat[i, j] = R[i, j] / r

print("Valores de r_i:")
print(r_i)

print("\nMatriz P_hat:")
print(P_hat)

print("\nSuma de filas de P_hat:")
print(P_hat.sum(axis=1))

Valores de r_i:
[5. 6. 4. 4.]

Matriz P_hat:
[[0.16666667 0.33333333 0.5        0.        ]
 [0.66666667 0.         0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.16666667 0.         0.5        0.33333333]]

Suma de filas de P_hat:
[1. 1. 1. 1.]


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Algoritmo de uniformización
</p>

<p style="font-size:18px;">
  El algoritmo suma términos de la serie hasta que la suma acumulada de probabilidades de Poisson sea mayor o igual que 1 - ε.
</p>

<p style="font-size:18px;">
  Esto garantiza que el error de aproximación sea menor o igual que ε.
</p>

In [4]:
def uniformizacion(P_hat, r, t, epsilon):
    n = P_hat.shape[0]

    # Paso 1
    k = 0
    c = math.exp(-r * t)
    suma = c

    # Paso 2
    A = np.eye(n)

    # Paso 3
    B = c * A

    # Paso 4 y 5
    while suma < 1 - epsilon:
        k = k + 1

        c = c * (r * t) / k
        A = A @ P_hat
        B = B + c * A

        suma = suma + c

    M = k
    return B, M, suma

<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Cálculo de P(0.5), P(1) y P(5)
</p>

<p style="font-size:18px;">
  Ahora aplicamos el algoritmo de uniformización para cada valor de t.
</p>

In [5]:
tiempos = [0.5, 1, 5]
resultados_uniformizacion = {}

for t in tiempos:
    P_t, M, suma = uniformizacion(P_hat, r, t, epsilon)
    resultados_uniformizacion[t] = P_t

    print(f"\nP({t}) con tolerancia epsilon = {epsilon}")
    print(f"Valor de M usado: {M}")
    print(f"Suma acumulada de probabilidades de Poisson: {suma}")

    print("\nMatriz P(t):")
    print(np.round(P_t, 6))

    print("\nSuma por filas:")
    print(np.round(P_t.sum(axis=1), 6))


P(0.5) con tolerancia epsilon = 1e-05
Valor de M usado: 13
Suma acumulada de probabilidades de Poisson: 0.9999965980853868

Matriz P(t):
[[0.250608 0.216964 0.386656 0.145769]
 [0.253134 0.23836  0.374408 0.134094]
 [0.169119 0.193614 0.4203   0.216964]
 [0.158017 0.157444 0.39833  0.286205]]

Suma por filas:
[0.999997 0.999997 0.999997 0.999997]

P(1) con tolerancia epsilon = 1e-05
Valor de M usado: 19
Suma acumulada de probabilidades de Poisson: 0.9999948198310631

Matriz P(t):
[[0.20615  0.203901 0.398708 0.191235]
 [0.208283 0.20534  0.397898 0.188474]
 [0.196758 0.198379 0.400957 0.203901]
 [0.192045 0.193996 0.401469 0.212483]]

Suma por filas:
[0.999995 0.999995 0.999995 0.999995]

P(5) con tolerancia epsilon = 1e-05
Valor de M usado: 56
Suma acumulada de probabilidades de Poisson: 0.9999926210449976

Matriz P(t):
[[0.199999 0.199999 0.399997 0.199999]
 [0.199999 0.199999 0.399997 0.199999]
 [0.199999 0.199999 0.399997 0.199999]
 [0.199999 0.199999 0.399997 0.199999]]

Suma por

<p style="color:#D12B2B; font-size:28px; font-weight:bold;">
  Verificación de Chapman-Kolmogorov
</p>

<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Se verifica si P(1) = P(0.5)P(0.5)
</p>

In [6]:
P_05 = resultados_uniformizacion[0.5]
P_1 = resultados_uniformizacion[1]

producto = P_05 @ P_05

print("P(1):")
print(np.round(P_1, 6))

print("\nP(0.5)P(0.5):")
print(np.round(producto, 6))

print("\nDiferencia P(1) - P(0.5)P(0.5):")
print(np.round(P_1 - producto, 10))

norma = np.linalg.norm(P_1 - producto)

print("\nNorma de la diferencia:")
print(norma)

P(1):
[[0.20615  0.203901 0.398708 0.191235]
 [0.208283 0.20534  0.397898 0.188474]
 [0.196758 0.198379 0.400957 0.203901]
 [0.192045 0.193996 0.401469 0.212483]]

P(0.5)P(0.5):
[[0.20615  0.203901 0.398707 0.191235]
 [0.208283 0.20534  0.397897 0.188473]
 [0.196757 0.198378 0.400957 0.203901]
 [0.192045 0.193996 0.401469 0.212483]]

Diferencia P(1) - P(0.5)P(0.5):
[[3.247e-07 3.247e-07 6.495e-07 3.247e-07]
 [3.247e-07 3.247e-07 6.495e-07 3.247e-07]
 [3.247e-07 3.247e-07 6.495e-07 3.247e-07]
 [3.247e-07 3.247e-07 6.495e-07 3.247e-07]]

Norma de la diferencia:
1.718308282173343e-06


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Conclusión de Chapman-Kolmogorov
</p>

In [7]:
if norma < 1e-4:
    print("Conclusión: Sí se verifica Chapman-Kolmogorov de forma aproximada.")
else:
    print("Conclusión: No se verifica exactamente, pero la diferencia se debe a la aproximación numérica.")

Conclusión: Sí se verifica Chapman-Kolmogorov de forma aproximada.


<p style="color:#D12B2B; font-size:28px; font-weight:bold;">
  Comparación con el ejercicio 3
</p>

<p style="font-size:18px;">
  En el ejercicio 3 se eligió M con la regla aproximada M ≈ max{rt + 5√rt, 20}.
</p>

<p style="font-size:18px;">
  Ahora el valor de M se obtiene automáticamente con la tolerancia ε = 0.00001.
</p>

In [8]:
def M_ejercicio_3(t, r):
    return math.ceil(max(r*t + 5*math.sqrt(r*t), 20))

print("Comparación de valores de M:")

for t in tiempos:
    M_regla = M_ejercicio_3(t, r)
    _, M_uniformizacion, _ = uniformizacion(P_hat, r, t, epsilon)

    print(f"\nt = {t}")
    print(f"M del ejercicio 3: {M_regla}")
    print(f"M por uniformización con epsilon = {epsilon}: {M_uniformizacion}")

Comparación de valores de M:

t = 0.5
M del ejercicio 3: 20
M por uniformización con epsilon = 1e-05: 13

t = 1
M del ejercicio 3: 20
M por uniformización con epsilon = 1e-05: 19

t = 5
M del ejercicio 3: 58
M por uniformización con epsilon = 1e-05: 56


<p style="color:#1A73E8; font-size:22px; font-weight:bold;">
  Conclusión final
</p>

<p style="font-size:18px;">
  El algoritmo de uniformización calcula P(t) sumando términos hasta que la cola de la distribución Poisson sea menor que ε.
</p>

<p style="font-size:18px;">
  Por eso, el valor de M no se elige de forma fija, sino que depende de t, de r y de la tolerancia solicitada.
</p>

<p style="font-size:18px;">
  Con ε = 0.00001, las matrices obtenidas son aproximaciones confiables de P(0.5), P(1) y P(5).
</p>